<?php

/**
 * @file
 * The core implementation for the RESTful user registration module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function restful_user_registration_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'restful' && $plugin_type == 'restful') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_permission().
 */
function restful_user_registration_permission() {
  return [
    'allowed to register user account' => [
      'title' => t('Allowed to register user account'),
    ],
    'allowed to update user account' => [
      'title' => t('Allowed to update user account')
    ],
  ];
}
